WebAppMVC/WebAppMVC/Models/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebAppMVC.Controllers;

namespace WebAppMVC.Models
{
   
    public class CartController : Controller
    {
        private Sports_Zone_DbEntities db = new Sports_Zone_DbEntities();
        // GET: Cart
        public ActionResult Index()
        {
            return View();
        }
        private int isExisting(string id)
        {
            List<Item> cart = (List<Item>)Session["cart"];
            for (int i = 0; i < cart.Count; i++)
            {
                if (cart[i].Product.ProId == id)
                {
            
                    return i;
                }    
            }
            return -1;
        }
        public ActionResult Delete(string id)
        {
            int index = isExisting(id);
            List<Item> cart = (List<Item>)Session["cart"];
            cart.RemoveAt(index);
            Session["cart"] = cart;
            return View("cart");
        }
        public ActionResult OrderNow(string id)
        {
            if (Session["cart"] == null)
            {
                List<Item> cart = new List<Item>();
                cart.Add(new Item(db.Products.Find(id), 1));
                Session["cart"] = cart;
               
            }
            else
            {
                List<Item> cart = (List<Item>)Session["cart"];
                int index = isExisting(id);
                if (index == -1)
                {
                    cart.Add(new Item(db.Products.Find(id), 1));
                }
                else 
                {
                    cart[index].quantity++;
                }
                Session["cart"] = cart;
            }
                return View("cart"); 
         

        }
        public ActionResult Order()
        {
            return RedirectToAction("UserSignIn","Users");
        }
        
        public ActionResult CheckOut()
        {
           
            return View();
        }
    }
}

WebAppMVC/WebAppMVC/Models/Product.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Carts = new HashSet<Cart>();
            this.Categories = new HashSet<Category>();
            this.Feedbacks = new HashSet<Feedback>();
        }
  
        public string ProId { get; set; }
     
        public string ProName { get; set; }
 
        public string ProDescription { get; set; }
    
        public Nullable<decimal> ProPrice { get; set; }
  
        public Nullable<int> Stock { get; set; }
        //[StringLength(9000)]
     
        public string ProPic { get; set; }
        //[NotMapped]
        //public HttpPostedFile EImgFile { get; set;}

    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cart> Carts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Category> Categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Feedback> Feedbacks { get; set; }
    }
}

WebAppMVC/WebAppMVC/Models/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebAppMVC.Filter;

namespace WebAppMVC.Models
{
    public class ProductsController : Controller
    {
        private Sports_Zone_DbEntities db = new Sports_Zone_DbEntities();

        // GET: Products
        public ActionResult Index()
        {
            return View(db.Products.ToList());
        }

        // GET: Products/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: Products/Create
        [OurAuthFilter]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [OurAuthFilter]
        public ActionResult Create([Bind(Include = "ProId,ProName,ProDescription,ProPrice,Stock,ProPic")] Product product, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                string filename = Path.GetFileName(file.FileName);
                string upath = Path.Combine(Server.MapPath("~/Upload"), filename);
                file.SaveAs(upath);
               
                db.Products.Add(product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(product);
        }

        // GET: Products/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProId,ProName,ProDescription,ProPrice,Stock,ProPic")] Product product)
        {
            if (ModelState.IsValid)
            {

                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(product);
        }

        // GET: Products/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Product product = db.Products.Find(id);
            db.Products.Remove(product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebAppMVC/WebAppMVC/Views/Products/Create.cshtml
@model WebAppMVC.Models.Product

@{
//ViewBag.Title = "Create";
}

<h2 class="text-center bg-success">Add Product</h2>


@using (Html.BeginForm("Create","Products", FormMethod.Post, new {enctype="multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @*<h4>Product</h4>*@
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ProId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Stock, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Stock, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Stock, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProPic, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
            <input type="file" name="file" id="file" required/>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @*@Html.ActionLink("Back to List", "Index")*@
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebAppMVC/WebAppMVC/Views/Products/Delete.cshtml
@model WebAppMVC.Models.Product

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Product</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProPrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Stock)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Stock)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProPic)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProPic)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebAppMVC/WebAppMVC/Views/Products/Details.cshtml
@model WebAppMVC.Models.Product

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Product</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProPrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Stock)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Stock)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProPic)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProPic)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ProId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WebAppMVC/WebAppMVC/Views/Products/Edit.cshtml
@model WebAppMVC.Models.Product

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ProId)

        <div class="form-group">
            @Html.LabelFor(model => model.ProName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Stock, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Stock, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Stock, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProPic, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProPic, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProPic, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebAppMVC/WebAppMVC/Views/Products/Index.cshtml
@model IEnumerable<WebAppMVC.Models.Product>

@{
    ViewBag.Title = "Index";
}

@*@using (Html.BeginForm("Index","Search",FormMethod.Post))
    {
        <span>Enter Product : </span>@Html.TextBox("text")
        <input type="submit" value="Search Products" />

    }*@
<h2 class="text-center bg-warning">All Products</h2>
@foreach (var item in Model)
{
    <div class="container">
        <div class="row" >
            <div class="col-md-3">
                <div class="ibox">
                    <div class="ibox-content product-box">
                        <div class="product-imitation">
                            <img src="~/Images/sports-balls-on-black-background_cczzxcfzx_6.5.jpg" / style="height:150px; width:150px">
                            @*<img scr="@Url.Content(item.ProPic)" />*@
                        </div>
                        <div class="product-desc">
                            <span class="product-price">
                                
                                @Html.DisplayFor(modelItem => item.ProPrice)
                            </span>
                            <small class="text-muted"> Stock: @Html.DisplayFor(modelItem => item.Stock)</small>
                            <a href="#" class="product-name"> @Html.DisplayFor(modelItem => item.ProName)</a>

                            <div class="small m-t-xs">
                                @Html.DisplayFor(modelItem => item.ProDescription)
                            </div>
                            <div class="m-t text-righ">
                                @if (Session["UserId"] != null)
                                {
                                    @Html.ActionLink("Add To Cart", "OrderNow", "Cart", new { id = item.ProId }, null)

                                }
                                else
                                {
                                    @Html.ActionLink("Add To Cart", "Order", "Cart")
                                }

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

WebAppMVC/WebAppMVC/Views/Products/Index1.cshtml
@model IEnumerable<WebAppMVC.Models.Product>

@{
//ViewBag.Title = "Index1";
}

<h2>Index1</h2>

<p>
    @*@Html.ActionLink("Create New", "Create")*@
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ProName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProDescription)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProPrice)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Stock)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ProName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ProDescription)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ProPrice)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Stock)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ProId }) |
            @Html.ActionLink("Details", "Details", new { id=item.ProId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ProId })
        </td>
    </tr>
}

</table>